### ISSUE TITLE
MS4 Feedback

### ISSUE THREAD

**Issue by Iadel95** [ubco-W2022T2-data301/project-group-group100#28]
## Feedback for Group 47

1. Notes from [Islam] on Feedback on the analysis:

Analysis 1:

- good job
- [x] clear warnings
- [x] few visualizations are present

Analysis 2:

- good job.

Analysis 3:

## Contracted Grade

1. What is your contracted grade?

- A+

2. Are you on track to satisfy all the requirements of your contracted grade?

- Yes, work isn't done but you're on the right track.

**Comment by beratcelik1** [comment]
Done.
