### ISSUE TITLE
Urgent: Missing Final Report

### ISSUE THREAD

**Issue by firasm** [ubco-W2022T2-data301/project-group-group100#29]
Hello,

Your project repository is currently missing the Final Report, as required in Milestone 6: https://firas.moosvi.com/courses/data301/2022_WT2/project/milestone06.html

Please submit your Final Report within 48 hours so we can asses your project - if you choose not to submit a final report, your grade will be downgraded to a B.

Thanks,

Dr. Moosvi

**Comment by beratcelik1** [comment]
Final report uploaded.
